version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - mridul89
    reviewers:
      - mridul89
    target-branch: main

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - mridul89
    reviewers:
      - mridul89
    target-branch: main
