name: Validations

on:
  push:
    branches:
      - main
  workflow_call:
  workflow_dispatch:

jobs:
  validations:
    name: Validations and Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate composer files
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: php-dev-${{ hashFiles('**/composer.*') }}

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install -o --prefer-dist --no-progress --no-suggest

      - name: Run test suite
        run: composer run-script test

      - name: Run style checks
        continue-on-error: true
        run: composer run-script check
